project:
  type: website
  output-dir: docs

website:
  title: "Gapminder Data Analysis"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Life Expectancy vs GDP"
        href: life-gdp.qmd
      - text: "Life Expectancy vs Population"
        href: life-population.qmd
      - text: "Country Analysis"
        href: country.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



